# Generated by Django 5.2.13 on 2026-04-22 05:53

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TitleEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "embedding_source",
                    models.CharField(
                        choices=[("overview", "Overview"), ("combined", "Combined")],
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("vector", pgvector.django.vector.VectorField(dimensions=1536)),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="catalog.title",
                    ),
                ),
            ],
            options={
                "unique_together": {("title", "embedding_source", "model_name")},
            },
        ),
    ]
