# Generated by Django 5.2.13 on 2026-04-22 19:54

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titleembedding",
            name="embedding_source",
            field=models.CharField(
                choices=[("overview", "Overview"), ("combined", "Combined")],
                default="combined",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="titleembedding",
            name="model_name",
            field=models.CharField(default="gemini-embedding-001", max_length=100),
        ),
        migrations.AlterField(
            model_name="titleembedding",
            name="vector",
            field=pgvector.django.vector.VectorField(dimensions=3072),
        ),
    ]
