# Generated by Django 5.2.13 on 2026-04-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tmdb_id", models.PositiveBigIntegerField(db_index=True, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("original_name", models.CharField(blank=True, max_length=255)),
                (
                    "media_type",
                    models.CharField(
                        choices=[("movie", "Movie"), ("tv", "TV")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=100)),
                ("overview", models.TextField(blank=True)),
                ("tagline", models.CharField(blank=True, max_length=500)),
                ("original_language", models.CharField(blank=True, max_length=20)),
                ("country_codes", models.JSONField(blank=True, default=list)),
                ("poster_url", models.URLField(blank=True)),
                ("backdrop_url", models.URLField(blank=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("first_air_date", models.DateField(blank=True, null=True)),
                ("last_air_date", models.DateField(blank=True, null=True)),
                ("runtime_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("episode_run_times", models.JSONField(blank=True, default=list)),
                ("seasons_count", models.PositiveIntegerField(blank=True, null=True)),
                ("episodes_count", models.PositiveIntegerField(blank=True, null=True)),
                ("age_rating", models.CharField(blank=True, max_length=50)),
                ("popularity", models.FloatField(db_index=True, default=0.0)),
                ("vote_average", models.FloatField(db_index=True, default=0.0)),
                ("vote_count", models.PositiveIntegerField(default=0)),
                ("is_adult", models.BooleanField(default=False)),
                ("raw_source_updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-popularity", "name"],
                "indexes": [
                    models.Index(
                        fields=["media_type", "release_date"],
                        name="catalog_tit_media_t_9e9b47_idx",
                    ),
                    models.Index(
                        fields=["media_type", "first_air_date"],
                        name="catalog_tit_media_t_aaf339_idx",
                    ),
                    models.Index(
                        fields=["vote_average", "vote_count"],
                        name="catalog_tit_vote_av_72a61a_idx",
                    ),
                ],
            },
        ),
    ]
