# Generated by Django 5.2.13 on 2026-04-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="title",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="titles", to="taxonomy.genre"
            ),
        ),
        migrations.AddField(
            model_name="title",
            name="keywords",
            field=models.ManyToManyField(
                blank=True, related_name="titles", to="taxonomy.keyword"
            ),
        ),
        migrations.AddField(
            model_name="title",
            name="themes",
            field=models.ManyToManyField(
                blank=True, related_name="titles", to="taxonomy.theme"
            ),
        ),
    ]
