# Generated by Django 5.2.13 on 2026-04-23 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_title_genres_title_keywords_title_themes"),
    ]

    operations = [
        migrations.CreateModel(
            name="TitleWatchProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country_code",
                    models.CharField(db_index=True, default="US", max_length=10),
                ),
                ("provider_type", models.CharField(db_index=True, max_length=20)),
                ("provider_id", models.PositiveIntegerField()),
                ("provider_name", models.CharField(max_length=255)),
                ("logo_path", models.CharField(blank=True, max_length=255)),
                ("display_priority", models.PositiveIntegerField(default=0)),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_providers",
                        to="catalog.title",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["title", "country_code", "provider_type"],
                        name="catalog_tit_title_i_39a719_idx",
                    )
                ],
                "unique_together": {
                    ("title", "country_code", "provider_type", "provider_id")
                },
            },
        ),
    ]
