# Generated by Django 5.2.13 on 2026-04-23 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_titlewatchprovider"),
    ]

    operations = [
        migrations.CreateModel(
            name="TitleNewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_name", models.CharField(max_length=255)),
                ("headline", models.CharField(max_length=500)),
                ("summary", models.TextField(blank=True)),
                ("url", models.URLField()),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_items",
                        to="catalog.title",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
