# Generated by Django 5.2.13 on 2026-04-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_titlenewsitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="titlewatchprovider",
            name="provider_link",
            field=models.URLField(blank=True),
        ),
    ]
