# Generated by Django 5.2.13 on 2026-04-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_titlewatchprovider_provider_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="titlewatchprovider",
            name="affiliate_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
