# Generated by Django 5.2.13 on 2026-04-29 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_titlewatchprovider_affiliate_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="TVSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("season_number", models.IntegerField(db_index=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("overview", models.TextField(blank=True)),
                ("poster_path", models.CharField(blank=True, max_length=500)),
                ("air_date", models.DateField(blank=True, null=True)),
                ("episode_count", models.IntegerField(default=0)),
                ("vote_average", models.FloatField(blank=True, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="catalog.title",
                    ),
                ),
            ],
            options={
                "ordering": ["season_number"],
                "unique_together": {("title", "season_number")},
            },
        ),
        migrations.CreateModel(
            name="TVEpisode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("season_number", models.IntegerField(db_index=True)),
                ("episode_number", models.IntegerField(db_index=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("overview", models.TextField(blank=True)),
                ("still_path", models.CharField(blank=True, max_length=500)),
                ("air_date", models.DateField(blank=True, null=True)),
                ("runtime", models.IntegerField(blank=True, null=True)),
                ("vote_average", models.FloatField(blank=True, null=True)),
                ("vote_count", models.IntegerField(blank=True, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="catalog.title",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="catalog.tvseason",
                    ),
                ),
            ],
            options={
                "ordering": ["season_number", "episode_number"],
                "unique_together": {("title", "season_number", "episode_number")},
            },
        ),
    ]
