# Generated by Codex on 2026-04-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPrivacySettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_profile", models.BooleanField(default=False)),
                ("show_ratings", models.BooleanField(default=False)),
                ("show_watchlist", models.BooleanField(default=False)),
                ("show_favorites", models.BooleanField(default=False)),
                ("show_watch_history", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("display_name", models.CharField(blank=True, max_length=120)),
                ("username_slug", models.SlugField(blank=True, max_length=120)),
                ("bio", models.TextField(blank=True)),
                ("avatar_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSiteSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "theme",
                    models.CharField(
                        choices=[("system", "System"), ("light", "Light"), ("dark", "Dark")],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("compact_cards", models.BooleanField(default=False)),
                ("autoplay_trailers", models.BooleanField(default=False)),
                ("reduce_animations", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserTastePreferences",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "preferred_format",
                    models.CharField(
                        choices=[("both", "Movies and TV"), ("movies", "Movies only"), ("tv", "TV only")],
                        default="both",
                        max_length=20,
                    ),
                ),
                (
                    "content_rating_preference",
                    models.CharField(
                        choices=[
                            ("any", "Any rating"),
                            ("family", "Family friendly"),
                            ("pg13", "PG-13 and below"),
                            ("mature", "R / mature allowed"),
                        ],
                        default="any",
                        max_length=20,
                    ),
                ),
                ("favorite_genres", models.JSONField(blank=True, default=list)),
                ("preferred_languages", models.JSONField(blank=True, default=list)),
                ("preferred_countries", models.JSONField(blank=True, default=list)),
                ("preferred_providers", models.JSONField(blank=True, default=list)),
                ("avoided_genres", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taste_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
