# Generated by Codex on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprivacysettings",
            name="show_reviews",
            field=models.BooleanField(default=False),
        ),
    ]
