# Generated by Codex on 2026-04-28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userprivacysettings_show_reviews"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprivacysettings",
            name="public_profile",
        ),
    ]
