# Generated by Django 5.2.13 on 2026-04-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tmdb_id", models.PositiveBigIntegerField(db_index=True, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("known_for_department", models.CharField(blank=True, max_length=100)),
                ("biography", models.TextField(blank=True)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("deathday", models.DateField(blank=True, null=True)),
                ("place_of_birth", models.CharField(blank=True, max_length=255)),
                ("profile_url", models.URLField(blank=True)),
                ("popularity", models.FloatField(db_index=True, default=0.0)),
            ],
            options={
                "ordering": ["-popularity", "name"],
            },
        ),
    ]
