# Generated by Django 5.2.13 on 2026-04-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawTMDBPayload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_entity",
                    models.CharField(
                        choices=[
                            ("movie", "Movie"),
                            ("tv", "TV"),
                            ("person", "Person"),
                            ("credit", "Credit"),
                            ("keyword", "Keyword"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("external_id", models.CharField(db_index=True, max_length=100)),
                ("payload", models.JSONField()),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source_entity", "external_id"],
                        name="ingestion_r_source__d93541_idx",
                    )
                ],
            },
        ),
    ]
