# Generated by Django 5.2.13 on 2026-04-22 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TitleCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("actor", "Actor"),
                            ("director", "Director"),
                            ("writer", "Writer"),
                            ("creator", "Creator"),
                            ("producer", "Producer"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("character_name", models.CharField(blank=True, max_length=255)),
                ("job_name", models.CharField(blank=True, max_length=255)),
                ("billing_order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="people.person",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="catalog.title",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["title", "role_type"],
                        name="credits_tit_title_i_105cc0_idx",
                    ),
                    models.Index(
                        fields=["person", "role_type"],
                        name="credits_tit_person__d3d19f_idx",
                    ),
                ],
                "unique_together": {
                    ("title", "person", "role_type", "character_name", "job_name")
                },
            },
        ),
    ]
